workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      vars:
        FLUTTER_VERSION: stable
      flutter: $FLUTTER_VERSION
      xcode: latest
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build .ipa
        script: flutter build ipa --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
